### ISSUE TITLE
Popis async vs parallel

### ISSUE THREAD

**Issue by meap** [rarous/rarousnet#1]
Pointa sdělení, tzn. rozdíl mezi asynchroním a paralením je IMO správně (nikdy jsem nad tím jak to vysvětlit dvakrát neuvažoval), ale podle mě je nešťastné do toho tahat vlákna, jelikož zde už se bavíme o konkrétní implementaci, která se bude lišit v Ruby (JRuby, MRI), JavaScriptu nebo C/C++.

Já z toho co jsi napsal automaticky získal pocit, že paralelní je tedy nové vlákno a asynchronií nikoli, což je nesmysl. Jak si správně napsal, netřeba zmiňovat vlákna, protože to je o úroveň níže a soustřeďme se na rozdíl mezi asynchroniím a paralelním.

Dá se jednoduše říct, že asynchronní je neblokující operace, která volajícího upozorní na své skončení, zatímco paralelní je rozdělení velké úlohy (CPU-bound) na několik souběžně běžících menších neblokujících úloh, kde tě ukončení může, ale také nemusí zajímat?

**Comment by rarous** [comment]
Článek byl psán s konkrétní implementací v .netu. Spíše se kladl za cíl vyvrátit myšlenku, že když spustím nový task, tak mám asynchronní volání, než nějakou definici. I asynchronní úlohy mohou běžet paralelně.

V původním konceptu jsem v některých částech měl ještě termín konkurence. :)

Sám s odstupem mám taky několik výhrad, ale v zásadě v tom nevidím nic zásadně nesprávnýho.

Dobrá definice všech těch pojmů je třeba v této knize: https://pragprog.com/book/pb7con/seven-concurrency-models-in-seven-weeks

**Comment by meap** [comment]
Jasně a paralelní úlohy mohou běžet asynchronně :) Tak jsem to asi jen z tvého článku prostě nepobral a neodnesl co jsem si odnést měl. Neříkám, že to máš blbě, jen, že jsem to nedal :)
